version: '3.9'

services:
  localstack:
    image: localstack/localstack:1.2.0
    ports:
      - 4566:4566
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  init-localstack:
    image: amazon/aws-cli
    entrypoint: sh
    command: /init-localstack.sh
    volumes:
      - ./init-localstack.sh:/init-localstack.sh
    depends_on:
      localstack:
        condition: service_started